<?php require_once 'config.php'; $stmt=$pdo->prepare("SELECT r.*, u.name as usname FROM reports r JOIN users u on u.user_id=r.user_id ORDER BY time");$stmt->execute();$recent=$stmt->fetchAll(PDO::FETCH_ASSOC);?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>CityCare – Issues</title>

  <!-- Tailwind CDN -->
  <script src="https://cdn.tailwindcss.com"></script>

  <!-- Custom tailwind config for your theme -->
  <script>
    tailwind.config = {
      theme: {
        extend: {
          colors: {
            cream: "#F5EFE6",
            beige: "#E8DFCA",
            blueSoft: "#6D94C5",
            blueLight: "#CBDCEB",
          }
        }
      }
    }
  </script>
</head>

<body class="bg-cream text-gray-800">

  <!-- NAVBAR -->
  <header class="w-full bg-blueSoft text-white shadow-md sticky top-0 z-20">
    <div class="max-w-6xl mx-auto px-6 py-4 flex justify-between items-center">
      <h1 class="text-2xl font-bold tracking-wide">CityCare</h1>
      <nav class="space-x-6 hidden sm:flex">
        <a href="index.php" class="hover:opacity-80 font-semibold">Home</a>
        <a href="reports.php" class="hover:opacity-80 font-semibold">Issues</a>
      </nav>
    </div>
  </header>

  <!-- PAGE HEADER -->
  <section class="bg-blueLight py-16 px-6 text-center">
    <h2 class="text-4xl font-extrabold text-blueSoft drop-shadow-lg">City Issues</h2>
    <p class="text-gray-700 mt-4 max-w-2xl mx-auto">
      Browse all reported issues, filter by category, or use the search bar to find specific concerns.
    </p>
  </section>

  <!-- FILTER + SEARCH -->
  <section class="max-w-6xl mx-auto px-6 mt-12">
    <div class="bg-beige p-6 rounded-xl shadow-lg border border-blueLight/40 grid gap-6 md:grid-cols-3">

      <!-- Category Filter -->
      <div>
        <label class="font-semibold">Filter by Category</label>
        <select id="filterCategory"
                class="w-full mt-2 p-3 rounded-lg border border-blueLight bg-cream focus:ring-2 focus:ring-blueSoft outline-none">
          <option value="all">All</option>
          <option>Pollution</option>
          <option>Broken Infrastructure</option>
          <option>Waste Management</option>
          <option>Public Safety</option>
          <option>Other</option>
        </select>
      </div>

      <!-- Search -->
      <div class="md:col-span-2">
        <label class="font-semibold">Search Issues</label>
        <input type="text" id="searchInput" placeholder="Type to search..." 
               class="w-full mt-2 p-3 rounded-lg border border-blueLight bg-cream focus:ring-2 focus:ring-blueSoft outline-none">
      </div>
    </div>
  </section>

  <!-- ISSUE LIST -->
  <section class="max-w-6xl mx-auto px-6 mt-12 pb-20">
    <h3 class="text-2xl font-bold text-blueSoft mb-6">All Issues</h3>

    <div id="issueList" class="grid gap-6 md:grid-cols-2 lg:grid-cols-3">

      <!-- Cards generated by JS -->

    </div>
  </section>

  <!-- FOOTER -->
  <footer class="bg-blueSoft text-white text-center py-6 mt-10 shadow-inner">
    CityCare © 2025 — Making cities cleaner and safer
  </footer>

  <!-- JS: Mock Data + Rendering + Filters -->
  <script>
    const issues = <?= json_encode(array_map(function($r) {
        return [
            "title" => $r["name"],       // or $r["usname"] depending on your DB columns
            "category" => $r["category"],
            "location" => $r["location"],
            "description" => $r["description"],
			"anonymity" => ((int)$r['anonymous'] === 1 ? "Anonymous" : $r['usname'])
        ];
    }, $recent), JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) ?>;
    const issueList = document.getElementById("issueList");

    function renderIssues(filteredIssues) {
      issueList.innerHTML = "";
      filteredIssues.forEach(issue => {
        const card = document.createElement("div");
        card.className = "bg-white/70 backdrop-blur-sm border border-blueLight/40 p-6 rounded-xl shadow-md hover:shadow-xl transition cursor-pointer";
        card.innerHTML = `
          <h4 class="text-xl font-bold text-blueSoft">${issue.title}</h4>
          <p class="mt-2 text-gray-700">${issue.description}</p>
          <p><span class="font-semibold">Category:</span> ${issue.category}</p>
          <p><span class="font-semibold">Location:</span> ${issue.location}</p>
		  <p>${issue.anonymity}</p>
        `;
        issueList.appendChild(card);
      });
    }

    // Initial render
    renderIssues(issues);

    // Filtering + Search
    document.getElementById("filterCategory").addEventListener("change", applyFilters);
    document.getElementById("searchInput").addEventListener("input", applyFilters);

    function applyFilters() {
      const category = document.getElementById("filterCategory").value.toLowerCase();
      const search = document.getElementById("searchInput").value.toLowerCase();

      const filtered = issues.filter(issue => {
        const matchesCategory = category === "all" || issue.category.toLowerCase() === category;
        const matchesSearch =
          issue.title.toLowerCase().includes(search) ||
          issue.description.toLowerCase().includes(search) ||
          issue.location.toLowerCase().includes(search);
        return matchesCategory && matchesSearch;
      });

      renderIssues(filtered);
    }
  </script>

</body>
</html>
